#!/bin/bash

if [$0 -ne '' && $0 -ne '--version'] then
PYCMD=$(cat <<EOF
import interpreter.parser as parser

parser.file = $0
file = open($0, "r")

parser(file.read())
EOF
)
else
PYCMD=$(cat <<EOF

EOF
)
fi

python3 -c "$PYCMD"
